name: polsterhof_auftrag
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  pdf: ^3.7.3
  get_storage:
  get: 4.6.1
  flutter: 
    sdk: flutter
  path_provider: ^2.0.9
  intl: ^0.17.0
  printing: ^5.7.5
  file_picker: ^4.5.1
  dio: ^4.0.6
dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

